### ISSUE TITLE
Upgrade to wpilib v2023.4.3

### ISSUE THREAD

**Issue by alantango** [frc-team7587/frc2023#10]

**Comment by alantango** [comment]
![Image](https://github.com/frc-team7587/frc2023/assets/56481094/23ed4e99-d55d-4f98-af53-2eafc738f61b)

**Comment by rqho** [comment]
![Image](https://github.com/frc-team7587/frc2023/assets/80137887/ba976935-45ec-4b12-8996-fdf3c92e7213)
